/** AUTO-GENERATED from domain DSL (generation/generate.mjs). Do not edit by hand. */
export const FIELD_LABELS: Record<string, string> = {
  "code": "Код вида оборудования",
  "commissionedAt": "Дата ввода в эксплуатацию",
  "completedAt": "Фактическая дата завершения",
  "contractor": "Подрядная организация (если внешний ремонт)",
  "description": "Описание работ / дефекта",
  "engineHoursAtRepair": "Наработка на момент ремонта, моточасов",
  "engineHoursSinceLastRepair": "Наработка с последнего ремонта, моточасов",
  "equipmentId": "Оборудование",
  "equipmentTypeCode": "Вид оборудования",
  "id": "Идентификатор",
  "inventoryNumber": "Инвентарный номер",
  "lastRepairAt": "Дата последнего ремонта",
  "location": "Место эксплуатации / скважина / куст",
  "maintenanceIntervalHours": "Периодичность ТО, моточасов",
  "manufacturer": "Производитель",
  "name": "Наименование единицы оборудования",
  "notes": "Примечания",
  "number": "Номер заявки",
  "overhaulIntervalHours": "Периодичность КР, моточасов",
  "plannedAt": "Плановая дата начала",
  "repairKind": "Вид ремонта",
  "serialNumber": "Заводской (серийный) номер",
  "startedAt": "Фактическая дата начала",
  "status": "Текущий статус",
  "totalEngineHours": "Общая наработка, моточасов",
};
